### ISSUE TITLE
Inconsistent QueryParam handling with $body

### ISSUE THREAD

**Issue by lathspell** [othercodes/rest#1]
You have get($url, $body) where $body is expanded by http_build_query() and used as  HTTP Query Parameter and post($url, $body) where $body is not used as Query Parameter but as HTTP Body.

How am I supposed to do a PUT request that uses both, Query Params and a HTTP Body?

Shouldn't post/put/delete all have an optional third parameter i.e. post($url, array $queryParams, $body=null)?

(of course, the quick fix is to add the Query Parameters to $url oneself when using POST but that's what I mean with "inconsistent")

**Comment by othercodes** [comment]
You must build the query string manually, the $body parameter, now only works in POST, PUT, and PATCH methods. If a POST call need for some reason also a query yuo must build the query string manually.
