### ISSUE TITLE
POST Files

### ISSUE THREAD

**Issue by c42759** [othercodes/rest#10]
I wonder if is possible with this package to execute a post sending a file, like a png?
Have you any example of that?

**Comment by othercodes** [comment]
Yes, you can do something like: 

```php
$http = new \OtherCode\Rest\Rest(new \OtherCode\Rest\Core\Configuration([
    'url' => 'http://your.endpoint.com/',
]));

$response = $http->post('/upload', [
    'file' => '@' . realpath('example.txt') . ';filename=newname.txt;type=text/plain'
]);
```
To send a file you must use @ followed by the absolute path to the file to send.

**Comment by c42759** [comment]
@othercodes Oh thanks, time to do some tests of my own :3
